### ISSUE TITLE
typo 错别字

### ISSUE THREAD

**Issue by adispring** [GuoYongfeng/book#1]
Do you want to request a feature or report a bug?
你希望向我报告BUG还是提交一个内容需求？
报告BUG

What is the current behavior?
目前的问题表现是什么样的？
《初识Node.js》 小节中 "Nnigx反向代理"，
Nngix 拼写错误

If the current behavior is a bug, please provide the steps to reproduce .
如果这是个确认的问题，请描述一下具体的文章位置或是复现的步骤。
在《初识Node.js》 小节中

What is the expected behavior?
你预期的效果是什么样的呢？
 "Nginx反向代理"

**Comment by GuoYongfeng** [comment]
你好，多谢反馈，已经解决并发布。
